version: "3.8"
 
services:
  wordpress-db:
    container_name: wordpress-db
    image: mysql
    volumes:
      - /usr/local/mysql/bin/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  wordpress:
    container_name: wordpress
    depends_on:
      - wordpress-db
    image: wordpress
    ports:
      - 8000:80
    restart: always
    volumes:
      #  - /usr/local/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /usr/local/wordpress/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    depends_on: 
      - wordpress-db
